on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: "4.1", cache-version: 1 }
          - { os: windows-latest, r: "4.2", cache-version: 1 }
          - { os: windows-latest, r: "4.3", cache-version: 1 }
          - { os: windows-latest, r: "4.4", cache-version: 1 }
          - {
              os: ubuntu-20.04,
              r: "release",
              rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest",
              cache-version: 3,
            }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.config.os }}-${{ matrix.config.r }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
          extra-repositories: "https://r.docker.stat.auckland.ac.nz"

      - name: Check version number
        run: |
          desc <- read.dcf("DESCRIPTION")
          v <- strsplit(desc[1, "Version"], ".")[[1]]
          if (length(v) < 3) {
            stop("Version number must have at least 3 components")
          }
        shell: Rscript {0}

      - name: Install gtk binaries, and RGtk2 from source if needed
        if: runner.os == 'Windows'
        uses: coactions/setup-xvfb@v1
        with:
          run: ./.github/install_gtk.cmd

      - name: Add GTK to PATH
        if: runner.os == 'Windows'
        run: echo "${{env.R_LIBS_USER}}\RGtk2\gtk\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo apt install libgtk2.0-dev xorg-dev libxml2-dev libnlopt-dev libcurl4-openssl-dev

      - uses: ./.github/actions/install
        env:
          GTK_PATH: ${{ runner.os == 'Windows' && 'D:\a\_temp\gtk' || '' }}
        with:
          cache-version: ${{ matrix.config.cache  }}
          # extra packages based on R version
          extra-packages: ${{ matrix.config.r == '4.1' && 'cran/MatrixModels@0.5-0' || '' }}
          packages: "deps::., any::sessioninfo, iNZightModules=?ignore, ."
          needs: |
            check
            dependencies
          install-pandoc: true
          lockfile-create-lib: ${{ env.R_LIBS_USER }}

      # - name: Query dependencies
      #   run: |
      #     install.packages('remotes')
      #     saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
      #   shell: Rscript {0}

      # - name: Cache R packages
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ env.R_LIBS_USER }}
      #     key: ${{ matrix.config.os }}-r-${{ matrix.config.r }}-${{ matrix.config.cache-version }}-${{ hashFiles('.github/depends.Rds') }}
      #     restore-keys: ${{ matrix.config.os }}-r-${{ matrix.config.r }}-${{ matrix.config.cache-version }}-

      # - name: Install system dependencies
      #   if: runner.os == 'Linux'
      #   env:
      #     RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
      #   run: |
      #     sudo apt install libgtk2.0-dev xorg-dev libxml2-dev libnlopt-dev libcurl4-openssl-dev

      # - name: Install RGtk2
      #   if: runner.os == 'Windows'
      #   shell: Rscript {0}
      #   run: |
      #     options(repos = "https://r.docker.stat.auckland.ac.nz")
      #     if (!requireNamespace("RGtk2", quietly = TRUE))
      #       install.packages("RGtk2")
      #     if (!requireNamespace("cairoDevice", quietly = TRUE))
      #       install.packages("cairoDevice")

      # - name: Install gtk binaries, and RGtk2 from source if needed
      #   if: runner.os == 'Windows'
      #   shell: bash
      #   run: ./.github/install_gtk.cmd

      # - name: Add GTK to PATH
      #   if: runner.os == 'Windows'
      #   run: echo "${{env.R_LIBS_USER}}\RGtk2\gtk\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # - name: Check RGtk2
      #   if: runner.os == 'Windows'
      #   run: |
      #     library(RGtk2)
      #     gtkWindowNew()
      #   shell: Rscript {0}

      # - name: Install dependencies
      #   uses: coactions/setup-xvfb@v1
      #   env:
      #     OS_TYPE: ${{ runner.os }}
      #   with:
      #     run: Rscript ./.github/install_deps.R

      # - name: Create iNZightVIT directory
      #   if: runner.os == 'Windows'
      #   run: try(dir.create(file.path("~", "Documents", "iNZightVIT"), recursive = TRUE))
      #   shell: Rscript {0}

      # - name: Check
      #   uses: coactions/setup-xvfb@v1
      #   env:
      #     _R_CHECK_CRAN_INCOMING_REMOTE_: false
      #   with:
      #     run: Rscript -e "rcmdcheck::rcmdcheck(args = c('--no-manual', '--no-multiarch'), error_on = 'warning', check_dir = 'check')"

      # - name: Upload check results
      #   if: failure()
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: ${{ matrix.config.os }}-r${{ matrix.config.r }}-results
      #     path: check
