on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: "4.1", cache-version: 1 }
          - { os: windows-latest, r: "4.2", cache-version: 1 }
          - { os: windows-latest, r: "4.3", cache-version: 1 }
          - { os: windows-latest, r: "4.4", cache-version: 1 }
          - {
              os: ubuntu-20.04,
              r: "release",
              rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest",
              cache-version: 3,
            }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.config.os }}-${{ matrix.config.r }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
          extra-repositories: "https://r.docker.stat.auckland.ac.nz"

      - name: Check version number
        run: |
          desc <- read.dcf("DESCRIPTION")
          v <- strsplit(desc[1, "Version"], ".")[[1]]
          if (length(v) < 3) {
            stop("Version number must have at least 3 components")
          }
        shell: Rscript {0}

      - name: Install gtk binaries, and RGtk2 from source if needed
        if: runner.os == 'Windows'
        uses: coactions/setup-xvfb@v1
        with:
          run: ./.github/install_gtk.cmd

      - name: Add GTK x64 to PATH
        if: runner.os == 'Windows'
        run: echo "D:\a\_temp\gtk\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo apt install libgtk2.0-dev xorg-dev libxml2-dev libnlopt-dev libcurl4-openssl-dev

      - uses: ./.github/actions/install
        env:
          GTK_PATH: ${{ runner.os == 'Windows' && '"D:/a/_temp/gtk"' || '' }}
        with:
          cache-version: ${{ matrix.config.cache  }}
          # extra packages based on R version
          extra-packages: ${{ matrix.config.r == '4.1' && 'cran/MatrixModels@0.5-0' || '' }}
          packages: "deps::., any::sessioninfo, iNZightModules=?ignore, ."
          needs: |
            check
            dependencies
          install-pandoc: true

      - name: Finalise GTK installation
        if: runner.os == 'Windows'
        shell: Rscript {0}
        run: |
          # move GTK from D:/a/_temp/gtk to ${{env.R_LIB_FOR_PAK}}/RGtk2/gtk
          cat("::group::Moving GTK and checking RGtk2\n")
          cat("Moving GTK to RGtk2 ...\n")
          list.files("D:/a/_temp/")
          list.files(Sys.getenv("R_LIBS_USER"))
          if (!file.rename(
            "D:/a/_temp/gtk",
            file.path(system.file(package = "RGtk2"), "gtk")
          )) {
            cat("::error::Failed to move GTK to RGtk2")
            quit(status = 1)
          }
          cat("Checking RGtk2 ...\n")
          library(RGtk2)
          w <- try(gtkWindowNew(), silent = TRUE)
          print(w)
          if (inherits(w, "try-error") || is.null(w)) {
            cat("::error::RGtk2 failed to load")
            quit(status = 1)
          }
          if (!"GdkWindow" %in% class(w$window)) {
            cat("::error::RGtk2 hasn't loaded correctly")
            quit(status = 1)
          }
          cat("::endgroup::\n")

      # - name: Check RGtk2
      #   if: runner.os == 'Windows'
      #   run: |
      #   shell: Rscript {0}

      # - name: Install dependencies
      #   uses: coactions/setup-xvfb@v1
      #   env:
      #     OS_TYPE: ${{ runner.os }}
      #   with:
      #     run: Rscript ./.github/install_deps.R

      # - name: Create iNZightVIT directory
      #   if: runner.os == 'Windows'
      #   run: try(dir.create(file.path("~", "Documents", "iNZightVIT"), recursive = TRUE))
      #   shell: Rscript {0}

      # - name: Check
      #   uses: coactions/setup-xvfb@v1
      #   env:
      #     _R_CHECK_CRAN_INCOMING_REMOTE_: false
      #   with:
      #     run: Rscript -e "rcmdcheck::rcmdcheck(args = c('--no-manual', '--no-multiarch'), error_on = 'warning', check_dir = 'check')"

      # - name: Upload check results
      #   if: failure()
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: ${{ matrix.config.os }}-r${{ matrix.config.r }}-results
      #     path: check
